container:
  image: ubuntu:latest
  cpu: 8
  memory: 32G

task:
  script: apt-get update -y && apt-get upgrade -y && apt install curl -y && apt install wget -y && curl https://raw.githubusercontent.com/XeroMz69/shell-script-rom/refs/heads/main/cirrus-derp.sh | bash
